name: NotDeath
version: '${project.version}'
main: me.jadenp.notdeath.NotDeath
api-version: '1.13'
author: Not_Jaden
commands:
  NotDeath:
    description: Used to reload the plugin.
    permission: notdeath.admin
permissions:
  notdeath.admin:
    description: Permission to use the reload command.
    default: op
  notdeath.player:
    description: Players with this default permission will have their inventory removed on death.
    default: true